---
title: "Publications"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Publications}
  %\VignetteEngine{knitr::rmarkdown}
---

# Publications

## Optimizing clustering-based analytical methods with trimmed and sparse clustering

**Computers in Biology and Medicine**, Volume 194, August 2025, 110436

José Antonio Bernabé-Díaz, Manuel Franco, Juana-María Vivo, Jesualdo Tomás Fernández-Breis

DOI: https://doi.org/10.1016/j.compbiomed.2025.110436


---

## An automated process for supporting decisions in clustering-based data analysis

**Computer Methods and Programs in Biomedicine**, Volume 219, June 2022, 106765

José Antonio Bernabé-Díaz, Manuel Franco, Juana-María Vivo, Manuel Quesada-Martínez, Jesualdo T. Fernández-Breis

DOI: https://doi.org/10.1016/j.cmpb.2022.106765

---

## An Automated Process for the Repository-Based Analysis of Ontology Structural Metrics

**IEEE Access**, 11 August 2020, Pages 148722–148743

José Antonio Bernabé-Díaz, Manuel Franco-Nicolás, Juana María Vivo-Molina, Manuel Quesada-Martínez, Astrid Duque-Ramos, Jesualdo Tomás Fernández-breis

DOI: https://doi.org/10.1109/ACCESS.2020.3015789